### ISSUE TITLE
talkだけmarkedを使用している

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-web#100]
markedだと`#`が効いたりするので`src/sites/common/text-parser.jade`を共通して使うようにする

**Comment by Petitsurume** [comment]
`#`とかが効くのが仕様では

**Comment by otofune** [comment]
@Petitsurume なんかh1とかh2とか全てが同じ太さになって気持ちになるし----とか入ったメールとかを送信すると太くなったりして不便があるのと、タイムラインと処理を統一したい

**Comment by otofune** [comment]
`#`、`[]()`文法などが利用できるのは意図しない動作で、デザインの崩壊やXSSなどを生み出す可能性があり、避けたい、タイムラインとの記法の統一を行いたい意思がある

**Comment by otofune** [comment]
いつかやるけどとりあえず今は時期が悪い
