### ISSUE TITLE
つらい

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#112]
h1のline-heightを1.2ぐらいにして、全体をdisplay:flexで囲んだ上でalign-itemsをcenterにしてほしい

![image](https://cloud.githubusercontent.com/assets/6993514/22183110/8b2d9e22-e0f9-11e6-9920-97687c4151a2.png)

**Comment by otofune** [comment]
jade: `src/common/views/home-widgets/my-status.jade`
div: class `misskey-home-widget`, id `widget-my-status`

**Comment by otofune** [comment]
ここ
https://github.com/misskey-delta/misskey-web/blob/14fae40a2a47c1fdb89e804033e9ec10c7b461ab/src/sites/desktop/pages/home/style.less#L179
