### ISSUE TITLE
トークを二回目開いた時に前回のを参照するようにして

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#114]
シングルトンみたいな感じ

**Comment by potato4d** [comment]
大量にiframeしてyou are an idiotごっこするのが飽きたという経緯があります。

**Comment by otofune** [comment]
トークのURL決め打ちやしそっちに処理追加かな

**Comment by Petitsurume** [comment]
複数人と同時にトークすること考えて

**Comment by potato4d** [comment]
@Petitsurume 隠し事なんてしたって仕方ねぇしもっと透明感のある発言をしようぜ

**Comment by potato4d** [comment]
@Petitsurume 大体のもの公開できるんだよなぁ（Web上に乗っかってるものが大半なので）

**Comment by Petitsurume** [comment]
@potato4d ~/.sshも公開できるんですか！？！？へぇーすごいですね

**Comment by potato4d** [comment]
@Petitsurume 
公開鍵認証は甘え、時代はパスワード認証

**Comment by Petitsurume** [comment]
@potato4d はい総当たり〜〜〜

**Comment by otofune** [comment]
しない
