### ISSUE TITLE
任意の拡張子のファイルがアップロードできる

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/Misskey-Web#122]
サーバー側で弾いてなくて、input[type="file"]で制限してるだけだからなんでも上げられるのでよろしくない、俺はUnityのインストーラーをあげた。

![image](https://cloud.githubusercontent.com/assets/6993514/22183334/f15ef858-e0fe-11e6-88b6-7d1efcbab3ef.png)

![image](https://cloud.githubusercontent.com/assets/6993514/22183335/f4942cfa-e0fe-11e6-93b5-92c598e6b1b3.png)

**Comment by otofune** [comment]
これ本来のドライブの仕様なんでアじゃね

**Comment by Petitsurume** [comment]
それ仕様だよ

**Comment by potato4d** [comment]
やばいでしょ

**Comment by otofune** [comment]
とりあえずドメインは分けてるけど他にｙａｂａｉポイント教えてほしe

**Comment by Petitsurume** [comment]
なんのためにドメイン分けてると思ってるの
