### ISSUE TITLE
寄付のお願いがsyuilo宛になってる

### ISSUE THREAD

**Issue by atnanasi** [misskey-delta/Misskey-Web#124]
よし、じゃあsyuiloに寄付してやるぜ〜

**Comment by otofune** [comment]
デスクトップのウィジェットかな

**Comment by otofune** [comment]
これは僕の寄付先がないのもそうですがユーザーが自由にカスタムできる範囲で主開発者だった、今も後期バー所のを開発してる彼をわざわざ消す意味もないのでアレです、ただ寄付自体の存在がいらないならわかるよ
