### ISSUE TITLE
これいるの

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#125]
<img width="428" alt="screen shot 2017-01-23 at 0 03 56" src="https://cloud.githubusercontent.com/assets/6993514/22183353/76df9f14-e0ff-11e6-9477-5f2677952e8b.png">

**Comment by atnanasi** [comment]
いらない

**Comment by Petitsurume** [comment]
微妙に便利かもしれないけどこれ開くキーボードショートカットはいらないよな

**Comment by otofune** [comment]
ショートカットは消した

**Comment by Petitsurume** [comment]
初心者さんとかgithub url忘れマンに便利だから端っこに追いやる程度にしといて

**Comment by otofune** [comment]
すでに端っこだからやるなら削除

**Comment by otofune** [comment]
ホットキー消したので誤って開くことはないだろう、消しません
