### ISSUE TITLE
Emojiに対応して欲しい

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#127]
要望です

**Comment by otofune** [comment]
わかるけど面倒そう…面倒そうじゃない？

**Comment by Petitsurume** [comment]
ここからぶっこ抜いていこうなhttps://github.com/github/gemoji/blob/master/db/emoji.json

**Comment by potato4d** [comment]
@Petitsurume 
これほしかったけどなくて自作考えてたけどあったのか

**Comment by otofune** [comment]
twemojiとともに利用でポイント高いになりそう

**Comment by otofune** [comment]
対応した #144
