### ISSUE TITLE
iOS版Safari「ホーム画面に追加」への対応

### ISSUE THREAD

**Issue by ghost** [misskey-delta/misskey-web#13]
以下のコードの挿入で半ネイティブ化出来そう

```
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```

![img_4234](https://cloud.githubusercontent.com/assets/12780727/17292764/eb28e1f8-5826-11e6-982f-46b72e76ae81.JPG)

**Comment by otofune** [comment]
@ToMeWelcome thx! 実装します
PR送ってくれてもいいのよ?

**Comment by potato4d** [comment]
あーそれいいね
ただキャッシュとCookieがSafariと別枠で持つ上、一旦Killされるとクリアされるので、
今のバグが多いモバイル版だとちょくちょくアプリのKillが必要そう

**Comment by ToMeWelcome** [comment]
@otofune 軽くソースコード眺めたけど、どこに挿入するのか分からなかったなんて口が裂けても言えない

**Comment by potato4d** [comment]
@ToMeWelcome 
(head内やねんで)

**Comment by otofune** [comment]
@ToMeWelcome
src/sites/base.jadeあたりに入れればいい気がする、もしくはsrc/sites/mobile/base.jade

**Comment by otofune** [comment]
リンクに飛ぶ際にSafariに遷移してしまうことが多々あるらしく、それの対策まで含めたらそうとう面倒そうなので一度テストしてみて使えそうなら入れます

**Comment by ToMeWelcome** [comment]
CSSとJSでモーダルウィンドウ作って簡易ブラウザを作ることでじつげn(ry

**Comment by potato4d** [comment]
リンクをフックしてJSで遷移させるとSafariに飛ばないんやで（逆に言えば普通に移動は全部飛ぶ）

**Comment by otofune** [comment]
それ絶対めんどいじゃんーーーーーーーー

**Comment by Petitsurume** [comment]
モーダルウィンドウってお前iframeの埋め込み禁止してるサイトどうするねん

**Comment by otofune** [comment]
辞めます
