### ISSUE TITLE
投稿のtextareaに制限がないせいでresizeで死ぬ

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#130]
textareaの右下のつまみで伸ばすと宇宙が爆発して世界が終わる

![image](https://cloud.githubusercontent.com/assets/6993514/22183417/3ee86526-e101-11e6-8f4d-6fce8ed03085.png)

**Comment by Petitsurume** [comment]
max-height:60vhくらいが妥当なのかな(適当)
