### ISSUE TITLE
通知領域のバグ

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#14]
# ブラウザ

Chrome 52
# 環境
- [x] デスクトップ版
- [ ] モバイル版
# 問題の詳細

![img](https://i.gyazo.com/9d6af45d556c0cce40f3d7b80cfc07c2.gif)

**Comment by Petitsurume** [comment]
タグ間違ってますよ

**Comment by otofune** [comment]
@Petitsurume Thx...
何故mobileがついていたのか、これがわからない
