### ISSUE TITLE
デスクトップから自分宛ての通知カウントを削除できない

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#142]
通知全部消しても無理だし終わった
<img width="1440" alt="screen shot 2017-02-12 at 21 38 38" src="https://cloud.githubusercontent.com/assets/6993514/22862110/b0829290-f16b-11e6-88c7-122e81fbc8af.png">

**Comment by potato4d** [comment]
ヘッダーの自分宛てのところ

**Comment by otofune** [comment]
それね、通知とは別枠でDBに収まってて、消すボタンがデスクトップ版にはないんですね～～～

**Comment by potato4d** [comment]
消せるようにしてほしい

**Comment by otofune** [comment]
俺も消したいしいい感じに
とりあえず現状ではモバイルけせますお
