### ISSUE TITLE
プロフィール編集画面で画像を設定したらスクロールができなくなる

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/misskey-web#147]
多分モーダル出すときに背景がスクロールしてしまわないように付与してるstyleもしくはclassを外し忘れてる（コードは見てないけど動作的にそんな感じ）

![image](https://gyazo.com/f8924befec4d7b1f46fa68af87210343.gif)

**Comment by otofune** [comment]
笑うやんこんなん…
