### ISSUE TITLE
特定の合字の表示に失敗する

### ISSUE THREAD

**Issue by Tosuke** [misskey-delta/misskey-web#176]
# ブラウザ
chrome系、firefoxでは発生せず、safari(ios)では発生せず
# デスクトップ版 or モバイル版
CSSの問題なので両方で発生しうる
# 問題の詳細
👨‍❤️‍👨などの合字が正常に表示できない(個々の絵文字に分離してしまう)

**Comment by Tosuke** [comment]
フォントの指定をsans-serifのみにしたらうまくいった

**Comment by otofune** [comment]
これmisskey側ってわけでもないので終了で
フォントの設定はよく出来るってのはあるのでいつかなおしたいのはあって、ただ全削除はWindowsでの表示がぶっ壊れるからあんまやりたくないのでCloseさせて頂きました

**Comment by otofune** [comment]
ああすいません、先程Windowsでの表示が壊れると言いましたが最近の変更でWindowsでのChromeの表示でのデフォルトフォントがメイリオに変わったんでした、Edgeもおそらくメイリオデフォルトだと思うのでデフォルトで問題が霧散霧消しているかも、取り込みます
