### ISSUE TITLE
投稿のURLプレビューで二重でドキュメントを作成してしまう

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-web#209]
同時に取りに来る人間が多い分、仕方がないんだが、どうにかして投稿時にfetchを走らせドキュメントが無い場合の読み込みをpendingし再試行して結果を返却するようなロジックを作って削減したい

**Comment by Petitsurume** [comment]
ランダムwait入れるぐらいしかない

**Comment by otofune** [comment]
この世の終わりだ

**Comment by otofune** [comment]
_idをURLにしてしまえば (primary keyの重複で) セーブが阻まれる筈なのでそれでいくのもあり

**Comment by otofune** [comment]
外部に移譲したい #281
