### ISSUE TITLE
prompt使うのやめる

### ISSUE THREAD

**Issue by Petitsurume** [misskey-delta/misskey-web#21]
# デスクトップ版 or モバイル版

モバイル
# 問題の詳細

なんかios9系のprompt()がどうも調子よくないっぽい？のでいっそのこといい感じに複数行入れられるようにする

**Comment by otofune** [comment]
@Petitsurume 
Androidでも不具合が起きる為割と深刻
投稿ページに飛ばすか、それともMisskeyデスクトップみたいな投稿欄を用意するかどちらがいいのか

**Comment by Petitsurume** [comment]
なんか右上のやつ押したらいい感じのがペローンって降りてくるみたいな(表現力虚無)

**Comment by potato4d** [comment]
モーダルでも良いけれど、取り敢えず差し当たっての対処で投稿ページに飛ばすのが良いんじゃないかな。
既に起きていて割りとhotfixみがある現象だけ対処しちゃって、その後に考えるでも遅くはないと思う。

**Comment by otofune** [comment]
@potato4d @petitsurume とりあえず、WIPコミットで投稿ページに飛ばすようにします

**Comment by potato4d** [comment]
@otofune 
replyについても、対象の投稿の詳細ページに行く感じで、?reply=1の場合はautoforcusとかどうかな？

**Comment by Petitsurume** [comment]
queryよりhashのほうがよさそう

**Comment by Petitsurume** [comment]
とりあえず
https://misskey.cf/i/post?noui
をiframeで埋め込んでいい感じなデザインにすればよさそう

**Comment by otofune** [comment]
@atnanasi が投稿ページに飛ぶようにしてくれました

**Comment by otofune** [comment]
やめた
