### ISSUE TITLE
新Misskeyはいいぞ

### ISSUE THREAD

**Issue by syuilo** [misskey-delta/misskey-web#306]
@otofune @potato4d @atnanasi (ぱっと見てコミットが見えた方だけ)
まずはじめに、現在まで開発・メンテナンスを続けてくださってありがとうございます(握手して周りたいくらいです)。
しかし、このMisskeyのバージョンは設計やコードの質ともに、今となっては非常に不本意な出来になっています。
このようなリポジトリに皆様の労力を消費させるのは**忍びなく**、開発・メンテナンスを続けてほしくありません。
もちろんMisskeyはMIT Licenseでフォークも自由なのですが、私としてはどうせならより良い新Misskeyの方に力を注いで欲しいと思っています。
既に運営なされているMisskeyインスタンスのデータ移行などの問題があるのは重々承知しています。(データ移行に際して私が何かお手伝いできることがあれば言いつけてください)

## TL;DR
[新Misskey](https://github.com/syuilo/misskey)へのご移行はご検討されていますでしょうか？もしそうなら、私に何かお手伝いできることがありますでしょうか？

(ここまでお読みいただきありがとうございます。そして移行を催促するWindows10みたいでごめんなさい。でも作者としては皆さんにより良いものを使ってもらいたいのです)

**Comment by syuilo** [comment]
新Misskeyは旧Misskeyに比べて機能的に劣っている部分もありますが、移行のご意向(ダジャレじゃなく)があれば、そこは急ピッチで開発を進める所存です

**Comment by otofune** [comment]
そうですか・・・

**Comment by potato4d** [comment]
Sorry, this repository is for English only.
