### ISSUE TITLE
RPモーダル表示時のPostに対してのアクションアイコンの表示がおかしい

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/Misskey-Web#42]
# ブラウザ
Mac Chrome v52

# デスクトップ版 or モバイル版
Desktop

# 問題の詳細

デベロッパーツールすら見てないけど、z-indexがおかしいとかかな、変に浮いてる。

<img width="1439" alt="2016-08-21 0 57 57" src="https://cloud.githubusercontent.com/assets/6993514/17832303/75f9b2b8-673a-11e6-8161-77433f5491dc.png">

**Comment by otofune** [comment]
@potato4d バックを暗くしているのにアイコンが暗くなってないのでは？
多分Font Awesomeなのでフォントカラー変更でどうにかならないかな

**Comment by otofune** [comment]
申し訳ない、主張側でないものに突っ込んでしまった…

**Comment by potato4d** [comment]
取り敢えず引越し祝いください

**Comment by otofune** [comment]
金が無い 宇宙バイブルシリーズ

**Comment by otofune** [comment]
ヤバい
![okimoti](https://cloud.githubusercontent.com/assets/15062473/18250890/ea1c5ab4-73c0-11e6-97da-f5b09ba90859.PNG)

**Comment by otofune** [comment]
fixed by 2a8cd18, thanks @p1ch-jp!
