### ISSUE TITLE
RPのモーダルダイアログが消してもDOM上に残ってる

### ISSUE THREAD

**Issue by Petitsurume** [misskey-delta/misskey-web#75]

**Comment by potato4d** [comment]
CSSの都合上、display値がnoneからnone以外に変更する場合はアニメーションが効かなくなるので、それを動かすためにopacityを変えてpointer-eventsをnoneにするなりz-indexを-1にするなりしてアニメーションを動作させるための処理だと思うから、これに関しては仕方ないと思う。

実際値が変わってるからコレに関してはどうしてもDOMに残したいならnextTick的な機構を用意するもしくはsetTimeoutを17ぐらいにして動かすしかないので終わりって感じなのでこれはこれで良いでしょ

**Comment by potato4d** [comment]
#misskey-post-form参照

**Comment by otofune** [comment]
仕様
