### ISSUE TITLE
フォロー/フォロワー一覧がゴミ

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/Misskey-Web#84]
ゴミ
<img width="599" alt="2017-01-08 22 24 38" src="https://cloud.githubusercontent.com/assets/6993514/21750206/4dc7b4e0-d5f1-11e6-8a48-09c9ea123423.png">

**Comment by Petitsurume** [comment]
これもうbox二列じゃなくて横目一杯使ったデザインにしたほうが良さそう

**Comment by otofune** [comment]
これ @p1ch-jp と無限に修正してたけど辛くなって放置されたやつ

**Comment by potato4d** [comment]
もう直したので
