### ISSUE TITLE
フロントサイドとかいう言葉が嫌い

### ISSUE THREAD

**Issue by potato4d** [misskey-delta/Misskey-Web#86]
https://github.com/misskey-delta/Misskey-Web/blob/master/gulpfile.ts#L27-L29

**Comment by otofune** [comment]
いい言葉にリプレイスしてください

**Comment by potato4d** [comment]
じゃあ
s/frontside/soresuki/g
にするから

**Comment by Petitsurume** [comment]
クライアントでいいんじゃね

**Comment by potato4d** [comment]
ただしい
