### ISSUE TITLE
masterブランチのロゴを緑色にしてしまう

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-web#96]
[以前存在したブランチ](https://github.com/armchair-philosophy/Misskey-Web/branch/link)のような感じで、あとベタな緑色からいい感じの緑色に変更したい

**Comment by Petitsurume** [comment]
ビルド時に設定の色情報取ってきてfaviconとか動的生成すればいいのでは？

**Comment by otofune** [comment]
@Petitsurume これさっき考えたんだけど、色だけ置換するの最悪かなあと思ったり

**Comment by Petitsurume** [comment]
@otofune 別にいいのでは

**Comment by otofune** [comment]
動的生成は考えたけどとりあえず面倒なのでパス
